apiVersion: v1
kind: Service
metadata:
  name: microservices-nodejs-pod
  namespace: my-application
spec:
  type: NodePort
  selector:
    app: microservices-nodejs-pod
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007